
apiVersion: v1
kind: Service
metadata:
  name: webhook-service
  namespace: kube-diagnoser
spec:
  ports:
    - port: 443
      targetPort: 9443
  selector:
    control-plane: kube-diagnoser
    mode: master
