
# Prometheus Monitor Service (Metrics)
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    control-plane: kube-diagnoser
  name: kube-diagnoser-metrics-monitor
  namespace: kube-diagnoser
spec:
  endpoints:
    - path: /metrics
      port: http
  selector:
    matchLabels:
      control-plane: kube-diagnoser
