# permissions for end users to edit diagnosissources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: diagnosissource-editor-role
rules:
- apiGroups:
  - diagnosis.netease.com
  resources:
  - diagnosissources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - diagnosis.netease.com
  resources:
  - diagnosissources/status
  verbs:
  - get
