# permissions for end users to view diagnosissources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: diagnosissource-viewer-role
rules:
- apiGroups:
  - diagnosis.netease.com
  resources:
  - diagnosissources
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - diagnosis.netease.com
  resources:
  - diagnosissources/status
  verbs:
  - get
