# permissions for end users to edit abnormalsources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: abnormalsource-editor-role
rules:
- apiGroups:
  - diagnosis.netease.com
  resources:
  - abnormalsources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - diagnosis.netease.com
  resources:
  - abnormalsources/status
  verbs:
  - get
