# permissions for end users to edit abnormals.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: abnormal-editor-role
rules:
- apiGroups:
  - diagnosis.netease.com
  resources:
  - abnormals
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - diagnosis.netease.com
  resources:
  - abnormals/status
  verbs:
  - get
