apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: kube-diagnoser
    mode: agent
  name: kube-diagnoser-agent-metrics-service
  namespace: kube-diagnoser
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    control-plane: kube-diagnoser
    mode: agent
