apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubediag-edit
  labels:
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
rules:
- apiGroups:
  - diagnosis.kubediag.org
  resources:
  - diagnoses
  - operations
  - operationsets
  - triggers
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - diagnosis.kubediag.org
  resources:
  - diagnoses/status
  - operations/status
  - operationsets/status
  - triggers/status
  verbs:
  - get

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: diagnosis-viewer-role
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
rules:
- apiGroups:
  - diagnosis.kubediag.org
  resources:
  - diagnoses
  - operations
  - operationsets
  - triggers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - diagnosis.kubediag.org
  resources:
  - diagnoses/status
  - operations/status
  - operationsets/status
  - triggers/status
  verbs:
  - get
