# permissions for end users to edit diagnosers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: diagnoser-editor-role
rules:
- apiGroups:
  - diagnosis.netease.com
  resources:
  - diagnosers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - diagnosis.netease.com
  resources:
  - diagnosers/status
  verbs:
  - get
