# permissions for end users to view diagnosers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: diagnoser-viewer-role
rules:
- apiGroups:
  - diagnosis.netease.com
  resources:
  - diagnosers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - diagnosis.netease.com
  resources:
  - diagnosers/status
  verbs:
  - get
