# permissions for end users to view informationcollectors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: informationcollector-viewer-role
rules:
- apiGroups:
  - diagnosis.netease.com
  resources:
  - informationcollectors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - diagnosis.netease.com
  resources:
  - informationcollectors/status
  verbs:
  - get
