# permissions for end users to view recoverers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: recoverer-viewer-role
rules:
- apiGroups:
  - diagnosis.netease.com
  resources:
  - recoverers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - diagnosis.netease.com
  resources:
  - recoverers/status
  verbs:
  - get
