# permissions for end users to edit recoverers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: recoverer-editor-role
rules:
- apiGroups:
  - diagnosis.netease.com
  resources:
  - recoverers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - diagnosis.netease.com
  resources:
  - recoverers/status
  verbs:
  - get
