apiVersion: diagnosis.netease.com/v1
kind: Abnormal
metadata:
  name: file-status-collection
spec:
  source: Custom
  skipInformationCollection: false
  skipDiagnosis: true
  skipRecovery: true
  assignedInformationCollectors:
  - name: file-status-collector
    namespace: kube-diagnoser
  nodeName: my-node
  context:
    filePathInformation:
    - "/var/lib/"
