apiVersion: diagnosis.netease.com/v1
kind: Diagnosis
metadata:
  name: go-profiler
spec:
  source: Custom
  profilers:
  - name: go-profiler
    type: InformationCollector
    go:
      source: http://127.0.0.1:8090/debug/pprof/heap
    timeoutSeconds: 60
    expirationSeconds: 300
  nodeName: my-node
