apiVersion: diagnosis.netease.com/v1
kind: OperationSet
metadata:
  name: go-profiler
spec:
  adjacencyList:
  - id: 0
    to:
    - 1
  - id: 1
    operation: go-profiler
---
apiVersion: diagnosis.netease.com/v1
kind: Diagnosis
metadata:
  name: go-profiler
spec: 
  parameters:
    goprofiler.expirationseconds: "7200"
    goprofiler.type: Heap
    goprofiler.source: https://10.0.2.15:6443
    goprofiler.tls.secretReference.namespace: kube-diagnoser
    goprofiler.tls.secretReference.name: apiserver-profiler-sa-token-qz2t9
  operationSet: go-profiler
  nodeName: my-node
