apiVersion: diagnosis.netease.com/v1
kind: Abnormal
metadata:
  name: pod-reference
spec:
  source: Custom
  commandExecutors:
  - command:
    - "kill"
    - "-10"
    - "1000"
    type: Recoverer
    timeoutSeconds: 5
  podReference:
    name: liveness-exec
    namespace: default
