apiVersion: diagnosis.kubediag.org/v1
kind: OperationSet
metadata:
  name: sonobuoy
spec:
  adjacencyList:
  - id: 0
    to:
    - 1
  - id: 1
    operation: sonobuoy-script
    to:
    - 2
  - id: 2
    operation: sonobuoy-diagnoser
---
apiVersion: diagnosis.kubediag.org/v1
kind: Diagnosis
metadata:
  name: sonobuoy
spec: 
  operationSet: sonobuoy
  nodeName: my-node
  parameters:
    "param.operation.sonobuoy.path": "/var/lib/kubediag"
    "param.sonobuoy_result_collector.expiration_seconds": "60"
    "param.sonobuoy_result_collector.result_dir": "/var/lib/kubediag/tmp/results"
    "param.sonobuoy_result_collector.plugin_e2e_file": "results_dump_e2e.yaml"
