apiVersion: diagnosis.netease.com/v1
kind: Operation
metadata:
  name: mount-info-collector
spec:
  processor:
    path: /processor/mountInfoCollector
    scheme: http
    timeoutSeconds: 60
