apiVersion: diagnosis.netease.com/v1
kind: Diagnoser
metadata:
  name: terminating-pod-diagnoser
  namespace: kube-diagnoser
spec:
  ip: 0.0.0.0
  port: "8090"
  path: /diagnoser/terminatingpoddiagnoser
  scheme: http
  timeoutSeconds: 60
