apiVersion: diagnosis.netease.com/v1
kind: Operation
metadata:
  name: http-operation
spec:
  processor:
    externalIP: http-operation.kube-diagnoser.svc.cluster.local
    externalPort: 80
    path: /
    scheme: http
    timeoutSeconds: 30
