apiVersion: diagnosis.kubediag.org/v1
kind: Operation
metadata:
  name: http-operation
spec:
  processor:
    httpServer:
      address: http-operation.kubediag.svc.cluster.local
      port: 80
      path: /
      scheme: http
    timeoutSeconds: 30
